<?php

/**
 * helpers/xendit.php
 *
 * Interacts with Xendit REST API for Invoices and Refunds using cURL.
 */

/**
 * Sends a POST request to Xendit API.
 *
 * @param string $endpoint The API endpoint path (e.g., '/v2/invoices').
 * @param array $payload The JSON payload.
 * @param array $headers Additional HTTP headers.
 * @return array|false The decoded JSON response or false on failure.
 */
function callXenditAPI(string $endpoint, array $payload, array $headers = [])
{
    $secretKey = $_ENV['XENDIT_SECRET_KEY'] ?? '';
    if (empty($secretKey)) {
        error_log('[Xendit Error] Secret Key is not configured in $_ENV.');
        return false;
    }

    $url = 'https://api.xendit.co' . $endpoint;
    $ch  = curl_init();

    // Default headers
    $defaultHeaders = [
        'Content-Type: application/json'
    ];
    $mergedHeaders = array_merge($defaultHeaders, $headers);

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
    curl_setopt($ch, CURLOPT_HTTPHEADER, $mergedHeaders);
    curl_setopt($ch, CURLOPT_USERPWD, $secretKey . ':');
    // 1-line reason: Enable SSL peer verification for cURL requests to prevent man-in-the-middle (MITM) attacks.
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 15);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $curlError = curl_error($ch);
    curl_close($ch);

    if ($response === false) {
        error_log("[Xendit cURL Error] endpoint={$endpoint} | error={$curlError}");
        return false;
    }

    $result = json_decode($response, true);

    if ($httpCode >= 200 && $httpCode < 300) {
        return $result;
    }

    error_log("[Xendit API Error] endpoint={$endpoint} | http_code={$httpCode} | response={$response}");
    return false;
}

/**
 * Creates a Xendit Invoice.
 *
 * @param string $external_id Unique identifier for the transaction.
 * @param int $amount Amount to charge in IDR.
 * @param string $description Description of the item.
 * @param string $email Payer's email address.
 * @param int $expiry Duration in seconds until expiration (default 24 hours).
 * @return array|false Invoice details or false on failure.
 */
function createXenditInvoice(string $external_id, int $amount, string $description, string $email = '', int $expiry = 86400)
{
    $app_url = rtrim($_ENV['APP_URL'] ?? 'http://localhost/Pasti_Info', '/');

    $payload = [
        'external_id'          => $external_id,
        'amount'               => $amount,
        'description'          => $description,
        'invoice_duration'     => $expiry,
        'currency'             => 'IDR',
        'callback_url'         => $app_url . '/controllers/xendit-webhook.php',
        'success_redirect_url' => $app_url . '/pages/home.php',
        'failure_redirect_url' => $app_url . '/pages/home.php'
    ];

    if (!empty($email)) {
        $payload['payer_email'] = $email;
    }

    return callXenditAPI('/v2/invoices', $payload);
}

/**
 * Issues a refund for a transaction associated with an invoice.
 *
 * @param string $invoice_id The Xendit Invoice ID.
 * @param int $amount The amount to refund in IDR.
 * @param string $reason Reason for refund.
 * @param string $reference_id Unique reference generated by our system.
 * @return array|false Refund details or false on failure.
 */
function refundXenditInvoice(string $invoice_id, int $amount, string $reason = 'OTHERS', string $reference_id = '')
{
    $payload = [
        'invoice_id'   => $invoice_id,
        'amount'       => $amount,
        'currency'     => 'IDR',
        'reason'       => $reason
    ];

    if (!empty($reference_id)) {
        $payload['reference_id'] = $reference_id;
    }

    return callXenditAPI('/refunds', $payload);
}

/**
 * Retrieves a Xendit Invoice.
 *
 * @param string $invoice_id The Xendit Invoice ID.
 * @return array|false The invoice details or false on failure.
 */
function getXenditInvoice(string $invoice_id)
{
    $secretKey = $_ENV['XENDIT_SECRET_KEY'] ?? '';
    if (empty($secretKey)) {
        error_log('[Xendit Error] Secret Key is not configured in $_ENV.');
        return false;
    }

    $url = 'https://api.xendit.co/v2/invoices/' . $invoice_id;
    $ch  = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERPWD, $secretKey . ':');
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // compatibility
    curl_setopt($ch, CURLOPT_TIMEOUT, 15);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $curlError = curl_error($ch);
    curl_close($ch);

    if ($response === false) {
        error_log("[Xendit cURL Error] Get invoice failed: error={$curlError}");
        return false;
    }

    $result = json_decode($response, true);
    if ($httpCode >= 200 && $httpCode < 300) {
        return $result;
    }

    error_log("[Xendit API Error] Get invoice failed: http_code={$httpCode} | response={$response}");
    return false;
}

